<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="roboarm">

	<xacro:property name="base_mass" value="100.0"/>
	<xacro:property name="base_height" value="0.1"/>
	<xacro:property name="base_length" value="0.25"/>
	<xacro:property name="base_width" value="0.25"/>

	<xacro:property name="hip_mass" value="10.0"/>
	<xacro:property name="hip_length" value="1.0"/>
	<xacro:property name="hip_radius" value="0.1"/>

	<xacro:property name="shoulder_mass" value="5.0"/>
	<xacro:property name="shoulder_length" value="0.9"/>
	<xacro:property name="shoulder_radius" value="0.09"/>

	<xacro:property name="elbow_mass" value="5.0"/>
	<xacro:property name="elbow_length" value="0.9"/>
	<xacro:property name="elbow_radius" value="0.1"/>

	<xacro:property name="pi" value="3.141492653589793"/>

	<link name="world"/>
	<link name="base_link">
		<inertial>
			<mass value="${base_mass}"/>
			<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
			<inertia ixx="0.0"
					 ixy="0.0"
					 ixz="0.0"
					 iyy="0.0"
					 iyz="0.0"
					 izz="0.0"/>
		</inertial>

		<visual name="base_link_visual">
			<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</visual>

		<collision name="base_link_collision">
			<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</collision>
	</link>

	<link name="hip_link">
		<inertial>
			<mass value="${hip_mass}"/>
			<origin xyz="0 0 ${hip_length/2}" rpy="0 0 0"/>
			<inertia ixx="0.0"
					 ixy="0.0"
					 ixz="0.0"
					 iyy="0.0"
					 iyz="0.0"
					 izz="${hip_mass*hip_radius*hip_radius/2}"/>
		</inertial>

		<visual name="hip_link_visual">
			<origin xyz="0 0 ${hip_length/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${hip_length}" radius="${hip_radius}"/>
			</geometry>
		</visual>

		<collision name="hip_link_collision">
			<origin xyz="0 0 ${hip_length/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${hip_length}" radius="${hip_radius}"/>
			</geometry>
		</collision>
	</link>

	<link name="shoulder_link">
		<inertial>
			<mass value="${shoulder_mass}"/>
			<origin xyz="${hip_radius+shoulder_radius} 0 ${shoulder_length/2-shoulder_radius}" rpy="0 0 0"/>
			<inertia ixx="0.0"
					 ixy="0.0"
					 ixz="0.0"
					 iyy="0.0"
					 iyz="0.0"
					 izz="0.0"/>
		</inertial>

		<visual name="shoulder_link_visual">
			<origin xyz="${hip_radius+shoulder_radius} 0 ${shoulder_length/2-shoulder_radius}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${shoulder_length}" radius="${shoulder_radius}"/>
			</geometry>
		</visual>

		<collision name="shoulder_link_collision">
			<origin xyz="${hip_radius+shoulder_radius} 0 ${shoulder_length/2-shoulder_radius}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${shoulder_length}" radius="${shoulder_radius}"/>
			</geometry>
		</collision>
	</link>

	<link name="elbow_link">
		<inertial>
			<mass value="${elbow_mass}"/>
			<origin xyz="0 0 ${elbow_length/2-elbow_radius}" rpy="0 0 0"/>
			<inertia ixx="0.0"
					 ixy="0.0"
					 ixz="0.0"
					 iyy="0.0"
					 iyz="0.0"
					 izz="0.0"/>
		</inertial>

		<visual name="elbow_link_visual">
			<origin xyz="0 0 ${elbow_length/2-elbow_radius}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${elbow_length}" radius="${elbow_radius}"/>
			</geometry>
		</visual>

		<collision name="elbow_link_collision">
			<origin xyz="0 0 ${elbow_length/2-elbow_radius}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${elbow_length}" radius="${elbow_radius}"/>
			</geometry>
		</collision>
	</link>

	<joint name="world_joint" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
	</joint>

	<joint name="hip_joint" type="continuous">
		<parent link="base_link"/>
		<child link="hip_link"/>
		<origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<joint name="shoulder_joint" type="revolute">
		<parent link="hip_link"/>
		<child link="shoulder_link"/>
		<origin xyz="0 0 ${hip_length-shoulder_radius}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<limit lower="${-pi}" upper="${pi}" velocity="10.0" effort="10.0"/>
	</joint>

	<joint name="elbow_joint" type="revolute">
		<parent link="shoulder_link"/>
		<child link="elbow_link"/>
		<origin xyz="0 0 ${shoulder_length-elbow_radius}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<limit lower="${-pi}" upper="${pi}" velocity="10.0" effort="10.0"/>
	</joint>

	<transmission name="hip_transmission">
		<type>transmission_interface/SimpleTransmission</type>
		
		<joint name="hip_joint">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
		</joint>

		<actuator name="hip_motor">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="shoulder_transmission">
		<type>transmission_interface/SimpleTransmission</type>
		
		<joint name="shoulder_joint">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
		</joint>

		<actuator name="shoulder_motor">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="elbow_transmission">
		<type>transmission_interface/SimpleTransmission</type>
		
		<joint name="elbow_joint">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
		</joint>

		<actuator name="elbow_motor">
			<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<gazebo>
		<static>false</static>

		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/roboarm</robotNamespace>
		</plugin>
	</gazebo>

</robot>