roboarm:
  joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - hip_joint
      - shoulder_joint
      - elbow_joint
      - wrist_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint