roboarm:
  joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - hip_joint
      - shoulder_joint
      - elbow_joint
      - wrist_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint

  gripper_controller:
    type: position_controllers/JointPositionController
    joint: gripper_lower_left_joint
    pid: {p: 10.0, i: 1.0, d: 0.5}